version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/${LOGIN}/data/wp_data:/var/www/html:ro
    secrets:
      - source: server.crt
        target: /etc/nginx/certs/server.crt
      - source: server.key
        target: /etc/nginx/certs/server.key
    networks:
      - inception-net
    restart: always

  mariadb:
    build: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password.txt
      - MYSQL_DATABASE=${WP_DB_NAME}
      - MYSQL_USER=${WP_DB_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password.txt
    volumes:
      - /home/${LOGIN}/data/wp_db_data:/var/lib/mysql
    secrets:
      - source: db_root_password
        target: db_root_password.txt
      - source: db_password
        target: db_password.txt
    networks:
      - inception-net
    restart: always

  wordpress:
    build: ./requirements/wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_DB_USER=${WP_DB_USER}
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password.txt
    volumes:
      - /home/${LOGIN}/data/wp_data:/var/www/html
    secrets:
      - source: db_password
        target: db_password.txt
    networks:
      - inception-net
    restart: always

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  server.crt:
    file: ../secrets/nginx/server.crt
  server.key:
    file: ../secrets/nginx/server.key

networks:
  inception-net:
    driver: bridge

