services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - /home/amema/data/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - /home/amema/data/wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - /home/amema/data/wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

networks:
  inception:
    driver: bridge

