services:
  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb
    env_file: ./srcs/.env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - /home/amema/data/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress
    env_file: ./srcs/.env
    secrets:
      - db_password
    volumes:
      - /home/amema/data/wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx
    env_file: ./srcs/.env
    volumes:
      - /home/amema/data/wordpress:/var/www/html
      - ./secrets/server.crt:/etc/nginx/certs/server.crt:ro
      - ./secrets/server.key:/etc/nginx/certs/server.key:ro
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt